# Generated by Django 3.2.11 on 2022-03-24 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('pos', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('team_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_playing', models.BooleanField(default=False)),
                ('credit', models.FloatField()),
                ('pos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.position')),
                ('team_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.team')),
            ],
        ),
    ]
