# Generated by Django 4.0.1 on 2022-03-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='cap',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='player',
            name='v_cap',
            field=models.BooleanField(default=True),
        ),
    ]
